### ISSUE TITLE
After Update I get "KeyError: 'bit_rate'`" when trying to record.

### ISSUE THREAD

**Issue by nectar9000** [Hillobar/Rope#13]
After "Space Worm" update I get "KeyError: 'bit_rate'`" when trying to record.
Playback works fine. 

The entire error message: 
`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "C:\AI\Rope\Rope\rope\core_working.py", line 52, in coordinator
    vm.play_video(action[0][1])
  File "C:\AI\Rope\Rope\rope\VideoManager.py", line 250, in play_video
    "-b:v", d['streams'][0]['bit_rate'],
KeyError: 'bit_rate'`

**Comment by Hillobar** [comment]
Should be fixed now, Just update VideoManager.py

**Comment by nectar9000** [comment]
> Should be fixed now, Just update VideoManager.py

Work again now, thanks!
